# Generated by Django 2.2.12 on 2020-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_parametr_is_affects_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparametr',
            options={'verbose_name': 'Вариант параметра', 'verbose_name_plural': 'Варианты параметра товара'},
        ),
        migrations.AddField(
            model_name='parametr',
            name='filter_by',
            field=models.BooleanField(default=False, verbose_name='Фильтровать по параметру?'),
        ),
        migrations.AddField(
            model_name='parametr',
            name='query_name',
            field=models.SlugField(default='', verbose_name='Query name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='parametres',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.ProductParametr', verbose_name='Параметры'),
        ),
        migrations.AlterUniqueTogether(
            name='productparametr',
            unique_together={('parametr', 'value')},
        ),
        migrations.RemoveField(
            model_name='productparametr',
            name='filter_by',
        ),
        migrations.RemoveField(
            model_name='productparametr',
            name='product',
        ),
    ]
