# Generated by Django 2.2.14 on 2020-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200622_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCombinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ManyToManyField(blank=True, related_name='combination_parametres', to='catalog.ProductParametr', verbose_name='Параметры')),
            ],
        ),
    ]
