# Generated by Django 2.2.14 on 2020-07-24 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200707_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена комплектации', 'verbose_name_plural': 'Цены комплектаций'},
        ),
        migrations.AlterModelOptions(
            name='pricecombinations',
            options={'verbose_name': 'Параметры комплектации', 'verbose_name_plural': 'Варианты комплектаций'},
        ),
        migrations.AddField(
            model_name='product',
            name='recommend_categories',
            field=models.ManyToManyField(blank=True, to=settings.ITCASE_CATALOG_CATEGORY_MODEL, verbose_name='Рекомендуем категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommend_products',
            field=models.ManyToManyField(blank=True, related_name='_product_recommend_products_+', to=settings.ITCASE_CATALOG_PRODUCT_MODEL, verbose_name='Рекомендуем товары'),
        ),
    ]
