# Generated by Django 2.2.14 on 2020-07-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200724_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице?'),
        ),
    ]
