# Generated by Django 2.2.14 on 2020-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200728_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
