# Generated by Django 2.2.14 on 2020-07-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_price_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_components',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf_instructtion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scheme',
        ),
    ]
