# Generated by Django 2.2.14 on 2020-08-05 10:08

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_measuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='Изображение'),
        ),
    ]
