# Generated by Django 2.1.15 on 2020-08-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200806_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAtribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('section_content', tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='Контeнт')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('show', models.BooleanField(default=False, verbose_name='Показывать?')),
            ],
            options={
                'verbose_name': 'Вкладка параметров',
                'verbose_name_plural': 'Вкладки параметров',
                'ordering': ['sort'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='sectionatribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.ITCASE_CATALOG_PRODUCT_MODEL, verbose_name='Товар'),
        ),
    ]
