# Generated by Django 2.1.15 on 2020-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_parametres',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.Parametr', verbose_name='Параметры для фильтра'),
        ),
    ]
