# Generated by Django 2.1.15 on 2020-08-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_optionalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommend_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
    ]
