# Generated by Django 2.1.15 on 2020-08-11 08:44

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200810_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparateParametrPicking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='separated_product_parametres', to='catalog.Parametr', verbose_name='Параметр')),
                ('parametr_value', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='parametr', chained_model_field='parametr', on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductParametr')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_parametres', to='catalog.Price', verbose_name='Цена комплектации')),
            ],
            options={
                'verbose_name': 'Параметр комплектаций',
                'verbose_name_plural': 'Параметры комплектаций',
            },
        ),
    ]
