# Generated by Django 2.1.15 on 2020-08-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_separateparametrpicking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='other_template',
            field=models.BooleanField(default=False, verbose_name='Выбор товаров'),
        ),
    ]
