# Generated by Django 2.1.15 on 2020-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_category_other_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Содержание тэга', verbose_name='Мета-дескриптор (description)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Содержание тэга', verbose_name='Мета-дескриптор (keywords)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_other',
            field=models.TextField(blank=True, help_text='HTML тэги', verbose_name='Мета-дескрипторы'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)'),
        ),
    ]
