# Generated by Django 2.1.15 on 2020-08-14 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200813_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySectionAtribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('content', tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='Контeнт')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.ITCASE_CATALOG_CATEGORY_MODEL, verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Вкладка',
                'verbose_name_plural': 'Вкладки',
                'ordering': ['sort'],
            },
        ),
        migrations.AlterField(
            model_name='sectionatribute',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать?'),
        ),
    ]
