# Generated by Django 2.1.15 on 2020-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200814_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество в наличии'),
        ),
    ]
