# Generated by Django 2.1.15 on 2020-08-17 08:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200814_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separateparametrpicking',
            options={'ordering': ['sort'], 'verbose_name': 'Параметр комплектаций', 'verbose_name_plural': 'Параметры комплектаций'},
        ),
        migrations.AddField(
            model_name='separateparametrpicking',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='separateparametrpicking',
            name='parametr_value',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='parametr', chained_model_field='parametr', on_delete=django.db.models.deletion.CASCADE, related_name='separated_product_parametres', to='catalog.ProductParametr'),
        ),
    ]
