# Generated by Django 2.2.15 on 2020-08-18 08:08

from django.conf import settings
from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter__slug__on__category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(related_name='products', to=settings.ITCASE_CATALOG_CATEGORY_MODEL, verbose_name='Категории товаров'),
        ),
    ]
