# Generated by Django 2.2.15 on 2020-08-18 08:08

from django.db import migrations


def forwards_func(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    db_alias = schema_editor.connection.alias
    for product in Product.objects.using(db_alias).iterator():
        product.categories.add(product.category)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_add__categories__to__product'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
