# Generated by Django 2.2.15 on 2020-08-18 08:40

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_make__slug__unique__on__product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='Описание'),
        ),
    ]
