# Generated by Django 2.1.15 on 2020-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание изображения'),
        ),
    ]
