# Generated by Django 2.1.15 on 2020-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_price_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать?'),
        ),
    ]
