# Generated by Django 2.2.15 on 2020-08-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_price_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('sort', 'name'), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['name'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='parametr',
            options={'ordering': ['name'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры товаров'},
        ),
        migrations.AlterModelOptions(
            name='productparametr',
            options={'ordering': ('parametr', 'value'), 'verbose_name': 'Вариант параметра', 'verbose_name_plural': 'Варианты параметра товара'},
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
