# Generated by Django 2.1.15 on 2020-08-27 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_add__active__to__category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения'),
        ),
        migrations.AddField(
            model_name='category',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата/время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения'),
        ),
        migrations.AddField(
            model_name='product',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата/время создания'),
            preserve_default=False,
        ),
    ]
