# Generated by Django 2.2.15 on 2020-09-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20200827_1734'),
    ]

    operations = [
        migrations.RenameField(model_name='category',
                               old_name='other_template',
                               new_name='template_groups_type_selector'),
    ]
