# Generated by Django 2.2.15 on 2020-09-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_add__template_groups_type_selector__to__category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template_categories_list',
            field=models.BooleanField(default=False, verbose_name='Шаблон только с категориями'),
        ),
        migrations.AlterField(
            model_name='category',
            name='template_groups_type_selector',
            field=models.BooleanField(default=False, verbose_name='Шаблон с категориями и товарами'),
        ),
    ]
