# Generated by Django 2.2.15 on 2020-09-08 10:29

from django.db import migrations


def forwards_func(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    db_alias = schema_editor.connection.alias
    for category in Category.objects.using(db_alias).filter(level=0):
        category.template_categories_list = category.children.filter(
            active=True).exists()
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_add__template_categories_list__to__category'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
