# Generated by Django 2.1.15 on 2020-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_add__filter_brand__to__category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание изображения'),
        ),
    ]
