# Generated by Django 2.2.16 on 2020-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_productimage_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Если отключёно, элемент не будет отображаться на сайте', verbose_name='Показывать'),
        ),
    ]
