# Generated by Django 2.1.15 on 2020-08-17 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import filebrowser.fields
import mptt.fields
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.ITCASE_PAGES_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='изображение')),
                ('image_mobile', filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='мобильное изображение')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('template', models.CharField(blank=True, max_length=255, verbose_name='HTML шаблон')),
                ('content', tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='Контент')),
                ('content_simple', models.TextField(blank=True, verbose_name='Текст')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('pages', mptt.fields.TreeManyToManyField(related_name='rotator_rotator_set', to=settings.ITCASE_PAGES_PAGE_MODEL, verbose_name='Страницы')),
            ],
            options={
                'verbose_name': 'Элемент ротатора',
                'verbose_name_plural': 'Элементы ротатора',
                'db_table': 'itcase_rotator_rotator',
                'ordering': ['position'],
                'abstract': False,
            },
            managers=[
                ('allobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
